using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using AuthService;
using AuthService.Interfaces.Service;
using AuthService.Services;
using CoreResults;
using EntityRepository.Context;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Swashbuckle.AspNetCore.Filters;
using Swashbuckle.AspNetCore.Swagger;
using TestProject.Models.Db;
using TestProject.Models.User;

namespace TestProject
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }
       
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<IDbContext, AuthDataContext>();
            services.AddScoped<IAuthRepository<User, UserRole>, IdentityUserService<User, Role, UserRole>>();
            services.AddScoped<IRoleRepository<Role>, IdentityRoleService<Role>>();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
           services.AddContextWithSwagger();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.ContextWithSwagger();
            app.UseMvc();
          
        }
    }
}
/* public void SwaggerService(IServiceCollection services)
        {
            services.AddSwaggerDocument();
            services.AddSwaggerExamples();
            services.ConfigureSwaggerGen(options => { options.CustomSchemaIds(m => m.FullName); });
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info
                {
                    Title = "Swagger XML Api Demo",
                    Version = "v1",
                    Description = "A simple \"Personnel department\" ASP.NET Core Web API",
                    TermsOfService = "None",
                    Contact = new Contact { Name = "Uzcard Team", Email = "", Url = "https://qrpay.uz" } //,
                    //License = new License { Name = "Use under LICX", Url = "https://qrpay.uz" }
                });

                c.AddSecurityDefinition("Bearer", new ApiKeyScheme
                {
                    Description =
                        "Заголовок авторизации JWT с использованием схемы Bearer. Пример: \"Authorization: Bearer { token }\"",
                    Name = "Authorization",
                    In = "header",
                    Type = "apiKey"
                });
                c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
                {
                    {"Bearer", new string[] { }}
                });

                c.ExampleFilters();

#pragma warning disable CS0618 // Type or member is obsolete
                c.OperationFilter<AddFileParamTypesOperationFilter
                >(); // Adds an Upload button to endpoints which have [AddSwaggerFileUploadButton]
#pragma warning restore CS0618 // Type or member is obsolete
                //c.OperationFilter<AddHeaderOperationFilter>("correlationId", "Correlation Id for the request", false); // adds any string you like to the request headers - in this case, a correlation id
                c.OperationFilter<AddResponseHeadersFilter>(); // [SwaggerResponseHeader]
                c.OperationFilter<SecurityRequirementsOperationFilter>(); // [SwaggerResponseHeader]
                //Locate the XML file being generated by ASP.NET...
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.XML";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                //... and tell Swagger to use those XML comments.
                c.IncludeXmlComments(xmlPath);
            });
        }*/
